### ISSUE TITLE
Uncaught TypeError: whitelist.find is not a function

### ISSUE THREAD

**Issue by stephenrs** [phoenixstormcrow/clone-event#1]
The whitelist prints to the console, and it's an array...something must be missing.

It happens on this section of the code:

```
      if (whitelist.find(function (el) {
            return (el === e.constructor.name);
          }) === undefined) {
            throw new TypeError("Unsupported event constructor: " +
              e.constructor.name);
      }
```

**Comment by phoenixstormcrow** [comment]
Let me look into this and see what's going on. Thanks for bringing it to my attention!

**Comment by phoenixstormcrow** [comment]
@stephenrs That should do it, let me know if it gives you any trouble.

**Comment by stephenrs** [comment]
Thanks for taking care of it, but I was in a hurry and ended up just using underscore.js's extend() function.

**Comment by phoenixstormcrow** [comment]
Can't say I blame you. I'll need to have a look at my settings, so that I can get notified of these kinds of issues sooner.
